import Head from "next/head";
import { useState } from "react";
import TagList from "../components/TagList";
import TweetBox from "../components/TweetBox";

export default function Home() {
	const [tweet, setTweet] = useState<string>("");
	const [selectedKeywords, setSelectedKeywords] = useState<string[]>([])
	return (
		<div className="h-screen bg-slate-400">
			<Head>
				<title>SimplesS</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<main className="flex flex-col md:flex-row h-full">
				<TweetBox setTweet={setTweet} selectedKeywords={selectedKeywords}/>
				<div className="bg-slate-200 flex flex-col flex-1 p-6">
					<h2 className="text-2xl mb-2 md:text-4xl md:my-4"> Related Keywords </h2>
					<TagList tweet={tweet} setSelectedKeywords={setSelectedKeywords}/>
				</div>
			</main>
		</div>
	);
}
