import Head from "next/head";
import { useState } from "react";
import TagList from "../components/TagList";
import TweetBox from "../components/TweetBox";

export default function Home() {
	const [tweet, setTweet] = useState<string>("");
	const [selectedKeywords, setSelectedKeywords] = useState<string[]>([])
	return (
		<div className="h-screen bg-slate-400">
			<Head>
				<title>SimplesS</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<main className="flex flex-col md:flex-row h-full">
				<TweetBox setTweet={setTweet} selectedKeywords={selectedKeywords}/>
				<div className="bg-slate-200 flex flex-col flex-1 p-6 lg:p-12">
					{
						tweet ? (		
							<TagList tweet={tweet} setSelectedKeywords={setSelectedKeywords}/>
						) : (
							<div className="pt-16 text-center">
								<h1 className="text-4xl mb-4"> Simpless </h1>
								<p className="text-2xl mb-24">
									Come up with the right hashtags to market your products.
								</p>
								<p> Start by typing a tweet </p>
							</div>
						)
					}

				</div>
			</main>
		</div>
	);
}
